pins:
  - pin: EECIV-1
    function: 12V all times

  - pin: EECIV-2
    id: F3
    class: switch_inputs
    ts_name: EECIV 1 Power Steering Switch
    function: Power Steering Switch

  - pin: EECIV-3
    id: F11
    class: event_inputs
    ts_name: EECIV 3 Vehicle Speed Sensor
    function: Vehicle Speed Sensor


  - pin: EECIV-4
    id: F13
    class: outputs
    ts_name: EECIV 4 Tacho (IDM)
    function: Tacho (IDM)


  - pin: EECIV-5
    id: F4
    class: switch_inputs
    ts_name: EECIV 5 Brake Switch Input
    function: Brake Switch Input


  - pin: EECIV-6
    function: VSS-

  - pin: EECIV-7
    id: EFI_ADC_12
    class: analog_inputs
    ts_name: EECIV 7 Engine Coolant Temperature (CLT)
    function: Engine Coolant Temperature (CLT)

  - pin: EECIV-8
    id: EFI_ADC_20
    class: analog_inputs
    ts_name: EECIV 8 TPS2
    function: TPS2


  - pin: EECIV-9
    function: MAF Ground

  - pin: EECIV-10
    id: C7
    class: outputs
    ts_name: EECIV 10 AC Clutch
    function: AC Clutch

  - pin: EECIV-11
    function: Speed Control Solenoid

  - pin: EECIV-12
    id: D11
    class: outputs
    ts_name: EECIV 12 Injector 3
    function: Injector 3

  - pin: EECIV-13
    id: D10
    class: outputs
    ts_name: EECIV 13 Injector 4
    function: Injector 4

  - pin: EECIV-14
    id: D9
    class: outputs
    ts_name: EECIV 14 Injector 5
    function: Injector 5

  - pin: EECIV-15
    id: F12
    class: outputs
    ts_name: EECIV 15 Injector 6
    function: Injector 6

  - pin: EECIV-16
    function: Ignition Ground

  - pin: EECIV-17
    function: VIP Test (MIL)

  - pin: EECIV-18
    id: EFI_ADC_8
    class: analog_inputs
    ts_name: EECIV 18 Octane Adjust (Flex)
    function: Octane Adjust (Flex)

  - pin: EECIV-19
    id: C9
    class:  outputs
    ts_name: EECIV 19 Fuel Pump Monitor
    function: Fuel Pump Monitor

  - pin: EECIV-20
    function: Case Ground

  - pin: EECIV-21
    id: G3
    class: outputs
    ts_name: EECIV 21 Idle (IAC)
    function: IAC

  - pin: EECIV-22
    id: G5
    class: outputs
    ts_name: EECIV 22 Low Speed Fuel Pump
    function: Low Speed Fuel Pump

  #- pin: EECIV-23
  #  id: EFI_ADC_33
  #  class: analog_inputs
  #  ts_name: EECIV 23 Knock Sensor
  #  function: Knock Sensor
    
  - pin: EECIV-24
    id: A6
    class: event_inputs
    ts_name: EECIV 24 Cam Sensor (CID)
    function: Cam Sensor (CID) 

  - pin: EECIV-25
    id: EFI_ADC_13
    class: analog_inputs
    ts_name: EECIV 25 Intake Air Temp (IAT)
    function: Intake Air Temp (IAT)

  - pin: EECIV-26
    function: VREF

  - pin: EECIV-27
    function: Pressure Feedback EGR Sensor (NC) 

  #- pin: EECIV-28
  #  id: EFI_ADC_32
  #  class: analog_inputs
  #  ts_name: EECIV 28 Speed Control Command Switch
  #  function: Speed Control Command Switch

  - pin: EECIV-29
    id: EFI_ADC_0
    class: analog_inputs
    ts_name: EECIV 29 HEGO 1 (Rear)
    function: HEGO 1 (Rear)

  - pin: EECIV-30
    id: F5
    class: switch_inputs
    ts_name: EECIV 30 Clutch Switch
    function: Clutch Switch Input

  - pin: EECIV-31
    function: Canister Purge Solenoid (NC) 

  - pin: EECIV-32
    id: G14
    class: outputs
    ts_name: EECIV 32 Secondaries (IMRC)
    function: IMRC

  - pin: EECIV-33
    function: EGR Valve Regulator Solenoid (NC)

  - pin: EECIV-34
    function: DC1-

  - pin: EECIV-35
    id: C6
    class: outputs
    ts_name: EECIV 35 Speed Control Vent Solenoid
    function: Speed Control Vent Solenoid

  - pin: EECIV-36
    id: B9
    class: outputs
    ts_name: EECIV 36 Spark Out (SPOUT)
    function: SPOUT

  - pin: EECIV-37
    id: EFI_ADC_5
    class: analog_inputs
    ts_name: EECIV 37 VBATT
    function: 12V in Start and Run

  - pin: EECIV-38
    function: DC1+

  - pin: EECIV-39
    function: Speed Control Command Switch Ground

  - pin: EECIV-40
    function: Power Ground

  - pin: EECIV-41
    id: G4
    class: outputs
    ts_name: EECIV 41 High Speed Fuel Pump
    function: HFP

  - pin: EECIV-42
    id: EFI_ADC_19
    class: analog_inputs
    ts_name: EECIV 42 PPS2
    function: PPS2

  - pin: EECIV-43
    id: EFI_ADC_1
    class: analog_inputs
    ts_name: EECIV 43 HEGO 2 (Front)
    function: HEGO 2 (Front)

  - pin: EECIV-44
    id: EFI_ADC_3
    class: analog_inputs
    ts_name: EECIV 44 PPS
    function: PPS

  - pin: EECIV-45
    id: EFI_ADC_10
    class: analog_inputs
    ts_name: EECIV 45 Barometric Sensor (BAP)
    function: BAP

  - pin: EECIV-46
    function: Signal Return

  - pin: EECIV-47
    id: EFI_ADC_4
    class: analog_inputs
    ts_name: EECIV 47 Throttle Position Sensor
    function: Throttle Position Sensor

  - pin: EECIV-48
    function: Self-Test Input Connector

  - pin: EECIV-49
    function: HEGO Sensor Ground

  - pin: EECIV-50
    id: EFI_ADC_14
    class: analog_inputs
    ts_name: EECIV 50 Mass Air Sensor (MAF)
    function: Mass Air Sensor (MAF) 

  - pin: EECIV-51
    id: C8
    class: outputs
    ts_name: EECIV 51 Speed Control Vacuum Solenoid
    function: Speed Control Vacuum Solenoid

  - pin: EECIV-52
    function: DC2-

  - pin: EECIV-53
    function: DC2+

  - pin: EECIV-54
    id: A8
    class: outputs
    ts_name: EECIV 54 WOT Cutout Relay
    function: WOT Cutout Relay

  - pin: EECIV-55
    id: G6
    class: outputs
    ts_name: EECIV 55 Fan
    function: FAN

  - pin: EECIV-56
    id: B1
    class: event_inputs
    ts_name: EECIV 56 (PIP)
    function: PIP

  - pin: EECIV-57
    function: 12V in Start and Run

  - pin: EECIV-58
    id: G7
    class:  outputs
    ts_name: EECIV 58 Injector 1
    function: Injector 1

  - pin: EECIV-59
    id: G8
    class:  outputs
    ts_name: EECIV 59 Injector 2
    function: Injector 2

  - pin: EECIV-60
    function: Power Ground

  - pin: PE10
    id: E10
    class:  outputs
    ts_name: 5V Ref Enable
    function: 5V Ref Enable
